components:
  git:
    source_dir: git
    destination: "~"
    method: copy
    backup: true
    description: Git configuration files
    dependencies: []
  nvim:
    source_dir: nvim
    destination: ~/.config/nvim
    method: symlink
    backup: true
    description: Neovim configuration
    dependencies: []
  zsh:
    source_dir: zsh
    destination: "~"
    method: symlink
    backup: true
    description: Zsh configuration
    dependencies: []
  tmux:
    source_dir: tmux
    destination: ~/.config/tmux
    method: symlink
    backup: true
    description: Tmux configuration
    dependencies: []
  vim:
    source_dir: vim
    destination: ~/.vim
    method: symlink
    backup: true
    description: Vim configuration
    dependencies: []
  ghostty:
    source_dir: ghostty
    destination: ~/.config/ghostty
    method: symlink
    backup: true
    description: Ghostty configuration
    dependencies: []
  mise:
    source_dir: mise
    destination: ~/.config/mise
    method: symlink
    backup: true
    description: Mise configuration
    dependencies: [] 
