" ===========================
"  vimrc
"  author: toshiemon18
" ===========================

source $PWD/rc/bundle_dein.vim
source $PWD/rc/bundles.vim
source $PWD/rc/filetypes.vim
source $PWD/rc/general.vim
source $PWD/rc/keybinds.vim
