" =======================
"         Python
" =======================
set nocindent
set autoindent
set nosmartindent
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
set completeopt-=preview
