# 基本はgithub.comのリポジトリを指定するだけ
# NeoBundleと同じっすね

# =================
#   システム周り
# =================
# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# dein-ui
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
    if dein#util#is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# denite.vim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
if = 'has("nvim")'
hook_source = 'source ~/.config/nvim/userautoload/plugin-denite.vim'

# ag.vim
[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

# C-__でカーソル行をコメントアウト
# tcomment.vim
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ファイルツリーを表示する
# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

# ステータスラインを良い感じするやつ
# lightline.vim
# [[plugins]]
# repo = 'itchyny/lightline.vim'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# 同時押しをサポートする
# vim-arpeggio
[[plugins]]
repo = 'kana/vim-arpeggio'

# vim-ref.vim
[[plugins]]
repo = 'thinca/vim-ref'

# text-objectを強化するやつ
# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# shabadou.vim
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# neoterm
[[plugins]]
repo = 'kassio/neoterm'

# fzf.vim
[[plugins]]
repo = "junegunn/fzf"
build = "./install --bin"
merged = "0"

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"

# ======================
# プログラミングサポート
# ======================
# neosnippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# neosnippets-snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# deoplete.vim
# Dark powered asynchronous completion framework for NeoVim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'sh install.sh'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'w0rp/ale'

# =================
#   HTML
#   CSS
# =================
# HTML5のシンタックスに対応
# html5.vim
[[plugins]]
repo = 'othree/html5.vim'

# 閉じタグを良い感じにアレするやつ
# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'

# CSS3のシンタックスに対応
# vim-css3-syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'

# =================
#   Markdown
# =================
# Markdownのためのプラグイン
# vim-markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

# Vimで文書を書く
# reedes/vim-pencil
[[plugins]]
repo = 'reedes/vim-pencil'

# Git-Flavored-Markdownをサポートする
[[plugins]]
repo = 'jtratner/vim-flavored-markdown'

# =================[
#   Git
# =================
# VimとGitを連携する
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/denite-git'

# =================
#   Others
# =================
# TOML対応
# toml.vim
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tyru/open-browser.vim'

# wakatime
[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'iyuuya/denite-rails'

