# 基本はgithub.comのリポジトリを指定するだけ
# NeoBundleと同じっすね

# =================
#   システム周り
# =================
# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# dein-ui
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
    if dein#util#is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = "source ~/.config/nvim/userautoload/plugin-coc.vim"
build = '''
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
if [ ! -f package.json ]
then
	cp ~/.config/nvim/dein_files/coc_package.json ./package.json
fi
npm install --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
'''

# ale
[[plugins]]
repo = 'dense-analysis/ale'

# defx.nvim
[[plugins]]
repo = 'ress997/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = "source ~/.config/nvim/userautoload/plugin-defx.vim"

# denite.vim
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/userautoload/plugin-denite.vim'

# denite-rails
# deniteのrails source
[[plugins]]
repo = '5t111111/denite-rails'
on_ft = ['ruby', 'slim']

# ag.vim
[[plugins]]
repo = 'rking/ag.vim'

# async.vim
[[plugins]]
repo = 'prabirshrestha/async.vim'
# C-__でカーソル行をコメントアウト
# tcomment.vim
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ファイルツリーを表示する
# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add="source ~/.config/nvim/userautoload/plugin-nerdtree.vim"

[[plugins]]
repo = 'ryanoasis/vim-devicons'


# ステータスラインを良い感じするやつ
# lightline.vim
# [[plugins]]
# repo = 'itchyny/lightline.vim'

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'

# text-objectを強化するやつ
# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# shabadou.vim
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# neoterm
[[plugins]]
repo = 'kassio/neoterm'
hook_add='source ~/.config/nvim/userautoload/plugin-neoterm.vim'

# fzf.vim
[[plugins]]
repo = "junegunn/fzf"
build = "./install --bin"
merged = "0"

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"
hook_add = 'source ~/.config/nvim/userautoload/plugin-fzf.vim'

# =================
#   Git
# =================
# VimとGitを連携する
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = "source ~/.config/nvim/userautoload/plugin-fugitive.vim"

[[plugins]]
repo = 'airblade/vim-gitgutter'

# =================
#   Others
# =================
# TOML対応
# toml.vim
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tyru/open-browser.vim'

# wakatime
[[plugins]]
repo = 'wakatime/vim-wakatime'

# Colors
[[plugins]]
repo = 'morhetz/gruvbox'
